### ISSUE TITLE
Cannot read properties of undefined (reading 'sects')

### ISSUE THREAD

**Issue by habsul-rignyr** [tloncorp/landscape-apps#1532] opened 2022-12-15 21:48 UTC
```
TypeError: Cannot read properties of undefined (reading 'sects')
    at Dvt (https://habsul.uqbar.lol/apps/groups/assets/index.6b96209d.js:1138:77101)
    at qH (https://habsul.uqbar.lol/apps/groups/assets/index.6b96209d.js:93:53297)
    at Yie (https://habsul.uqbar.lol/apps/groups/assets/index.6b96209d.js:97:8857)
    at Rie (https://habsul.uqbar.lol/apps/groups/assets/index.6b96209d.js:97:964)
    at P6e (https://habsul.uqbar.lol/apps/groups/assets/index.6b96209d.js:97:887)
    at _w (https://habsul.uqbar.lol/apps/groups/assets/index.6b96209d.js:97:737)
    at UG (https://habsul.uqbar.lol/apps/groups/assets/index.6b96209d.js:95:10947)
    at Kd (https://habsul.uqbar.lol/apps/groups/assets/index.6b96209d.js:95:8466)
    at l8 (https://habsul.uqbar.lol/apps/groups/assets/index.6b96209d.js:97:15965)
    at https://habsul.uqbar.lol/apps/groups/assets/index.6b96209d.js:97:17629
```

**Comment by jamesacklin** [comment] 2022-12-15 21:56
@habsul-rignyr Thank you, should be fixed by #1521

(Dupe of #1513)

**Closed by jamesacklin** 2022-12-15 21:56 UTC
Labels: bug
