### ISSUE TITLE
chat: occasional double-render

### ISSUE THREAD

**Issue by baudtack** [tloncorp/landscape-apps#1497] opened 2022-12-14 22:37 UTC
Often in talk and groups messages will display twice, sometimes back to back, sometimes out of order.

![image](https://user-images.githubusercontent.com/32079/207729871-98a10d2d-dac9-411f-ac85-bf4755f5c421.png)

**Comment by arthyn** [comment] 2023-01-20 22:50
dupe of #1430

**Closed by arthyn** 2023-01-20 22:50 UTC
Labels: bug, chat
