### ISSUE TITLE
hark: multiple notifications on group events

### ISSUE THREAD

**Issue by nartesfasrum** [tloncorp/landscape-apps#1447] opened 2022-12-12 20:40 UTC
**Describe the bug, optionally with screenshots**

Receiving multiple notifications in Groups for some group events, but not all. 

An example from ~nartes-fasrum-dozzod-sorwet:

![image](https://user-images.githubusercontent.com/80287270/207149472-7b76d1fe-0602-48ac-abed-024977017683.png)

An example from ~nartes-fasrum:

![image](https://user-images.githubusercontent.com/80287270/207149541-95c82b64-f947-4c09-856d-b4fe5dfe28ca.png)

**To Reproduce**
1. Go to the root Groups page at \[url\]/apps/groups.
2. See that multiple notifications have appeared for a single event.

**Expected behavior**
I expected to receive only one notification per event.

**Additional context:**
- Ship type: moon & planet (so far)
- Instance type: self-hosted on CLI
- OS/browser: Brave on Linux

**Comment by rdp-studio** [comment] 2022-12-22 05:01
I have encountered a similar situation and cannot set the message as read.
![image](https://user-images.githubusercontent.com/67402215/209060628-81ed3be6-6e19-49be-84d8-3db1961791d4.png)

**Comment by tomholford** [comment] 2023-01-03 23:37
Followed up with @nartesfasrum out of band to get a repro, but seems that it's no longer happening for now:

>i haven't had it happen in a while, and the relevant notifications seem to have disappeared from both the ships i took screenshots from actually

Also reached out to @rdp-studio, if neither has a current repro this can be shelved for now.

**Comment by thelifeandtimes** [comment] 2023-01-03 23:43
I am still experiencing the inability to mark notifications as read from the grid notifications view, but that might be a slightly different issue that @rdp-studio just alluded to?
<img width="865" alt="image" src="https://user-images.githubusercontent.com/82244264/210459532-c28859df-77fb-4499-8d7e-48fd418e982c.png">

**Comment by jamesacklin** [comment] 2023-01-04 02:03
@thelifeandtimes It is, but we have both automatic and manual fixes coming for that list soon.

**Comment by tomholford** [comment] 2023-01-05 22:23
@jamesacklin Still unable to repro, and after reaching out to the reporters it seems like it hasn't happened in some time. Moved to Awaiting Info.

**Comment by thelifeandtimes** [comment] 2023-01-05 23:49
Just adding here since it is notification related; for whatever update just went out, a bunch of my group DMs just reverted their unread status'. LMK if it would be preferable to write up in greater detail as a new issue.

**Comment by arthyn** [comment] 2023-01-06 20:57
@thelifeandtimes they never had unreads implemented so that would be why. I should have marked them all as read though so that you wouldn't have to go read them all. we may add a button for this.

**Comment by jamesacklin** [comment] 2023-01-23 15:45
Moving to the product backlog. Reproduction is rare and ultimately these duplicates get binned with the automatic hark-clearing (moves out of historical view). It's annoying and mysterious nonetheless.

**Closed** 2023-02-23 17:15 UTC
Labels: bug, needs-repro, notifications
