### ISSUE TITLE
Formatting on profile view is broken

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1368] opened 2022-12-09 00:53 UTC
**Describe the bug, optionally with screenshots**
- Write a profile
- Observe the formatting get thrown out
<img width="551" alt="Screenshot 2022-12-08 at 4 53 20 PM" src="https://user-images.githubusercontent.com/441466/206598113-3e4d060a-6c88-4b57-8f63-6eb74cc85ec3.png">

**Comment by jamesacklin** [comment] 2022-12-09 01:03
Dupe of #1036

**Closed by jamesacklin** 2022-12-09 01:03 UTC
Labels: bug
