### ISSUE TITLE
codeblock bug when trying to encase a sig.

### ISSUE THREAD

**Issue by thelifeandtimes** [tloncorp/landscape-apps#1589] opened 2022-12-27 00:57 UTC
**Describe the bug, optionally with screenshots**
If trying to send a check of the sig, `~`, via an inline codeblock, it tries to autofill a ship mention. 
**To Reproduce**
1. Go to the chat text submission box. type `\`~\``
2. See that the ship-mention selection dialog pops up. Hit `esc` to prevent auto complete.
3. Hit `enter` with the expectation of sending the `~`. See it autofill a `@p` anyways.

**Expected behavior**
Expected behavior is for the code backticks and implied codeblock to take precedence over mentions, including autocomplete funtionality. If a `@p` is enclosed by backticks, no selection dialog should appear, not should any autocomplete functionality trigger.

**Additional context:**
- Ship type: Planet
- Instance type: Self-hosted on Ubuntu 22.04
- OS/browser: Brave Version 1.45.123 Chromium: 107.0.5304.110 (Official Build) (arm64)

**Comment by jamesacklin** [comment] 2022-12-27 12:47
Dupe of #1405, thank you

**Closed by jamesacklin** 2022-12-27 12:47 UTC
Labels: bug
