### ISSUE TITLE
Double-posting of other ships' messages

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape-apps#1685] opened 2023-01-12 05:42 UTC
**Describe the bug, optionally with screenshots**
Sometimes, other people's messages will appear as double-posts or double-notifications until tab refresh.

![example 1](https://0x0.st/o7pq.png)
![example 2](https://0x0.st/o7pb.png)

**To Reproduce**
Unsure - it happens randomly.

**Expected behavior**
Should only ever see one copy of any post.

**Additional context:**
- Ship type = planet
- Instance type = self-hosted(Tlon-hosted/self-hosted with Port/CLI)
- Chormium-based browser on Pop!_OS 20.10

**Comment by jamesacklin** [comment] 2023-01-12 15:50
Dupe of #1497

**Closed by jamesacklin** 2023-01-12 15:50 UTC
Labels: bug
