### ISSUE TITLE
No groups found using search

### ISSUE THREAD

**Issue by Urbposter** [tloncorp/landscape-apps#1844] opened 2023-02-01 05:59 UTC
When searching for groups, using the search dialog, none are found.

**To Reproduce**
Launch moon locally with urbit binary
Open landscape via web interface
Search for groups to join, by host, e.g. ~bitbet-bolbel (hosts urbit-community)
None will be found.

**Comment by tomholford** [comment] 2023-02-01 09:47
@Urbposter Thanks for flagging. Do other known ships return results? e.g., ~middev's Forge, ~rondev's Group Discovery

Also, are you able to |hi any of the hosts from your dojo?

**Comment by Urbposter** [comment] 2023-02-01 19:29
Thanks for the help.

Trying to get groups from ~middev, ~rondev:

```
peek bad result
/app/hark/hoon:<[109 40].[109 67]>
/app/hark/hoon:<[109 5].[109 68]>
/app/hark/hoon:<[98 3].[113 5]>
/app/hark/hoon:<[97 3].[113 5]>
/sys/vane/gall/hoon:<[1.151 26].[1.151 60]>
out=[acked=%.n path=/gangs/index/~middev]
subscribe wire not unique
%groups
/gangs/index/~middev
[p=~middev q=%groups]
error in %groups
%watch-not-unique
! subscribe wire not unique
! %groups
! /gangs/index/~middev
! [p=~middev q=%groups]
out=[acked=%.n path=/gangs/index/~rondev]
subscribe wire not unique
%groups
/gangs/index/~rondev
[p=~rondev q=%groups]
error in %groups
%watch-not-unique
! subscribe wire not unique
! %groups
! /gangs/index/~rondev
! [p=~rondev q=%groups]

```
Output of +vat %groups:
```
> +vat %groups
%groups
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        ~
  %cz hash:         0vf.qnl07.7d8ps.i8m1f.kbv18.kj270.37g0m.sl5eh.ktpkr.vd3t0.4emm0
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~sogryp-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~sogryp-dister-dozzod-dozzod
  source desk:      %groups
  source aeon:      0
  kids desk:        ~
  pending updates:  ~[[%zuse 415]]
```
::


And, it seems there are connectivity issues:

```
> |hi ~wet
>=
> |hi ~middev
>=
> |hi ~zod
>=
```

**Comment by Urbposter** [comment] 2023-02-01 23:14
Update: fixed connectivity by creating a new moon. (I suspect the old moon was booted twice -- oops)

I can now reach sponsor planet, and ~wet, ~zod, etc.

Still cannot join any groups though.

**Comment by Urbposter** [comment] 2023-02-03 01:23
Second update:
Groups now joinable. Had to wait approx minutes for that to work.

**Comment by tomholford** [comment] 2023-02-03 15:15
Closing as work as intended

**Closed by tomholford** 2023-02-03 15:15 UTC
Labels: bug
