### ISSUE TITLE
Host Moon & Planet Views Differ

### ISSUE THREAD

**Issue by minderfolden** [tloncorp/landscape-apps#1486] opened 2022-12-14 16:35 UTC
**Describe the bug, optionally with screenshots**
My group is hosted on a moon, and my planet is an admin. I can update the group image from my moon, but the change is not reflected on my planet. I can change the channel arrangement & set view filtering to "arranged" from the moon, but the change doesn't show up on the planet. I also had to have my planet leave a moon-hosted notebook and rejoin in order to see a new post.  

**To Reproduce**
no idea

**Expected behavior**
Admins to make changes and have them stick.

**Additional context:**
- Ship type moon & planet
- Instance type Digital Ocean Droplet
- OS/browser Debian

**Comment by zalberico** [comment] 2022-12-14 16:43
Might be a duplicate of #1386

**Comment by bonbud-macryg** [comment] 2022-12-14 16:44
Channel visibility issue potentially related to #1401?

**Closed** 2022-12-15 16:18 UTC
Labels: bug
