### ISSUE TITLE
Unknown language: `markdown` is not registered

### ISSUE THREAD

**Issue by eamsden** [tloncorp/landscape-apps#2126] opened 2023-03-14 18:27 UTC
```
Error: Unknown language: `markdown` is not registered
    at b1e.yxt [as highlight] (http://peregrine:8080/apps/groups/assets/index.f67c0ed6.js:1150:253330)
    at http://peregrine:8080/apps/groups/assets/index.f67c0ed6.js:1151:8362
    at gR (http://peregrine:8080/apps/groups/assets/index.f67c0ed6.js:93:53252)
    at JG (http://peregrine:8080/apps/groups/assets/index.f67c0ed6.js:93:62788)
    at pae (http://peregrine:8080/apps/groups/assets/index.f67c0ed6.js:93:62114)
    at bX (http://peregrine:8080/apps/groups/assets/index.f67c0ed6.js:93:61697)
    at Nae (http://peregrine:8080/apps/groups/assets/index.f67c0ed6.js:97:12048)
    at Tae (http://peregrine:8080/apps/groups/assets/index.f67c0ed6.js:97:964)
    at DSe (http://peregrine:8080/apps/groups/assets/index.f67c0ed6.js:97:887)
    at Lw (http://peregrine:8080/apps/groups/assets/index.f67c0ed6.js:97:737)
```

![image](https://user-images.githubusercontent.com/54573/225102457-28480394-4810-4021-84a8-a9119da1361f.png)
from the ~ramlyx-sibdyt/guild group

**Comment by jamesacklin** [comment] 2023-03-14 22:32
Duplicate of #2121

**Closed by jamesacklin** 2023-03-14 22:32 UTC
Labels: bug
