### ISSUE TITLE
groups: large notebook indexes don't load

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1623] opened 2023-01-04 18:55 UTC
- Join ~rondev/group-discovery
- Look at the Main Index channel
- Observe that you only see a small subset of the notebooks

This is a large index that had a ton of notebooks - I suspect only a subset are rendering?

**Comment by jamesacklin** [comment] 2023-01-04 18:56
Dupe of #1458, fixed by #1554

**Closed by jamesacklin** 2023-01-04 18:56 UTC
Labels: bug
