### ISSUE TITLE
Diary: submitting a post that uses an indented bullet - Invalid content for node bulletList: <bulletList(listItem(paragraph("This works the oth

### ISSUE THREAD

**Issue by vcavallo** [tloncorp/landscape-apps#1646] opened 2023-01-06 15:19 UTC
The string referenced here `"This works the oth [...]"` is an indented bullet point in a larger list of bullet points. 

```
RangeError: Invalid content for node bulletList: <bulletList(listItem(paragraph("This works the oth
    at nh.check (https://sogrum-savluc.me/apps/groups/assets/index.e70a0985.js:68:57649)
    at https://sogrum-savluc.me/apps/groups/assets/index.e70a0985.js:68:57997
    at Qe.forEach (https://sogrum-savluc.me/apps/groups/assets/index.e70a0985.js:68:44143)
    at nh.check (https://sogrum-savluc.me/apps/groups/assets/index.e70a0985.js:68:57984)
    at https://sogrum-savluc.me/apps/groups/assets/index.e70a0985.js:168:5580
    at Array.forEach (<anonymous>)
    at https://sogrum-savluc.me/apps/groups/assets/index.e70a0985.js:168:5566
    at Object.insertContentAt (https://sogrum-savluc.me/apps/groups/assets/index.e70a0985.js:165:8054)
    at https://sogrum-savluc.me/apps/groups/assets/index.e70a0985.js:168:4392
    at Object.insertContent (https://sogrum-savluc.me/apps/groups/assets/index.e70a0985.js:165:7432)
```

**Comment by jamesacklin** [comment] 2023-01-06 17:26
Looks like a duplicate of #1598 but thank you for the additional context (indented bullet-point).

**Closed by jamesacklin** 2023-01-06 17:26 UTC
Labels: bug
