### ISSUE TITLE
Right arrow key when writing a comment on a gallery item sends you to the next item

### ISSUE THREAD

**Issue by galenwp** [tloncorp/landscape-apps#2415] opened 2023-04-27 00:08 UTC
**Describe the bug, optionally with screenshots**
The right arrow will take you to the next item when you're trying to edit text in a comment on a gallery item.

**Additional context:**
- OS/browser: Safari on MacOS

**Comment by jamesacklin** [comment] 2023-04-27 01:26
Duplicate of #1885

**Closed** 2023-04-27 01:27 UTC
Labels: bug
