### ISSUE TITLE
Unknown language: `nock` is not registered

### ISSUE THREAD

**Issue by matthew-levan** [tloncorp/landscape-apps#2848] opened 2023-09-05 16:46 UTC
App: Groups
  Version: 4.4.1
  Vere Version: undefined
  Hash: 0v1e.tcpr8.0f10a.v3pbd.oelin.ibrq6.0u0os.4dsu6.kldg3.vv877.h3ter
  Synced From: ~sogryp-dister-dozzod-dozzod
  Location: /apps/groups/groups/~dister-dozzod-lapdeg/core-academy/channels/diary/~dister-dozzod-lapdeg/kernschule/note/170141184506392250869000021080929206272

  ```
Error: Unknown language: `nock` is not registered
    at fn.Wn [as highlight] (https://mastyr-bottec.coeli.network/apps/groups/assets/refractor-1d9f97e5.js:3:85108)
    at https://mastyr-bottec.coeli.network/apps/groups/assets/index-9786b591.js:72:38565
    at Mu (https://mastyr-bottec.coeli.network/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:30:19470)
    at Fl (https://mastyr-bottec.coeli.network/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:3134)
    at vp (https://mastyr-bottec.coeli.network/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:2350)
    at Dc (https://mastyr-bottec.coeli.network/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:1892)
    at Bp (https://mastyr-bottec.coeli.network/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:47113)
    at Tp (https://mastyr-bottec.coeli.network/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:39610)
    at gh (https://mastyr-bottec.coeli.network/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:39538)
    at So (https://mastyr-bottec.coeli.network/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:39393)
```

**Comment by jamesacklin** [comment] 2023-09-05 18:47
Duplicate of #2844

**Closed by jamesacklin** 2023-09-05 18:47 UTC
Labels: bug
