### ISSUE TITLE
Error loading notebook in Guild group

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#2122] opened 2023-03-14 16:36 UTC
**Describe the bug, optionally with screenshots**
When trying to load the "Release Process March 2023" notebook, I get a JavaScript "Encountered error:Unknown language: `markdown` is not registered" error. Other notebooks in this channel load succesfully. 

**To Reproduce**
1. Go to '/1/group/~ramlyx-sibdyt/guild'
2. Click on Build: Bulletin Board
3. Select Release Process March 2023

![Screenshot 2023-03-14 at 9 32 57 AM](https://user-images.githubusercontent.com/1903610/225074697-07b32391-b19a-4d8b-adf1-19505e48b634.png)
 
2.8.2
0v6.ft3j1.dvmj1.26tfq.bkugs.ei2va.lkeg3.ku6sr.2jlmn.olepc.8j82a
~marnec-dozzod-marzod

**Comment by jamesacklin** [comment] 2023-03-14 17:21
Dupe of #2121

**Closed by jamesacklin** 2023-03-14 17:21 UTC
Labels: bug
