### ISSUE TITLE
groups: "Create New Group" final step button is broken

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#2259] opened 2023-04-06 17:57 UTC
**Describe the bug, optionally with screenshots**
On the last step of group creation, it appears that the "submit" button is broken — I can't click on it, press "Enter" to submit the form, or proceed in any way.

Watch the video below to see this bug in action:

https://user-images.githubusercontent.com/1195363/230457241-5e31a06b-a889-4cb0-8a4a-4486be1a7d2e.mov

**To Reproduce**
1. Ensure you're syncing %groups from `~wannec-dozzod-marzod`
2. At the root of the Groups app, create a new group
3. Provide all of the mandatory default info
4. On the last/third step, if the button doesn't appear (as seen in the vid above), you've repro'd the issue

**Expected behavior**
I expect this button to not disappear under any circumstances

**Additional context:**
- Ship: planet — `~fabled-faster`
- Instance type: GCP
- MacOS Ventura — 13.2.1 (22D68)
- Chromium Engine Version 111.0.5563.64

**Comment by patosullivan** [comment] 2023-04-06 19:25
dupe of #2258

**Closed by patosullivan** 2023-04-06 19:25 UTC
Labels: bug
