### ISSUE TITLE
notebooks: URLs don't wrap, breaks mobile view

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#1793] opened 2023-01-26 02:21 UTC
![Screenshot_20230125-201343_Brave.png](https://user-images.githubusercontent.com/1221094/214743047-c7cf82c0-6882-4b2f-b4a0-d4358ed0e552.png)

**Comment by jamesacklin** [comment] 2023-02-02 14:01
Duplicate of #1837. Even though this is the older issue, there's more info there.

**Closed by jamesacklin** 2023-02-02 14:01 UTC
Labels: bug
