### ISSUE TITLE
Cannot destructure property 'title' of 'e' as it is undefined.

### ISSUE THREAD

**Issue by wca4a** [tloncorp/landscape-apps#2516] opened 2023-05-15 17:27 UTC
```
TypeError: Cannot destructure property 'title' of 'e' as it is undefined.
    at ae (https://malmur-halmex.tlon.network/apps/groups/assets/grid.15aa2d16.js:1:1610)
    at Kl (https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at mf (https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:8723)
    at pf (https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
    at rn (https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:730)
    at sl (https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:21:10884)
    at https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38716
    at e.unstable_runWithPriority (https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:8:3811)
    at _r (https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38494)
```

**Comment by jamesacklin** [comment] 2023-05-16 16:53
Duplicate of #2483. This is due out with v3.3.0 of Groups and Talk, which is now going through internal testing.

**Closed by jamesacklin** 2023-05-16 16:54 UTC
Labels: bug
