### ISSUE TITLE
Rendering a published note

### ISSUE THREAD

**Issue by marisarow** [tloncorp/landscape-apps#2269] opened 2023-04-07 16:15 UTC
**Describe the bug, optionally with screenshots**
After making changes to an existing note and pressing publish/save, the new updates do not render. It takes a hard refresh to show the updates which makes using notebook as an editor quite cumbersome. 

**To Reproduce**
1. Open a note
2. Edit note
3. Click publish
4. View note - unchanged
5. Hard refresh - view note changed

**Expected behavior**
I would expect my updates to show. It's quite a scary moment when I'm writing an entire document here and I press publish to see that there is only the first paragraph from my last save rendered. It makes me lose trust in the software immediately in a huge way.

**Comment by urcades** [comment] 2023-04-28 02:23
Duplicate of #2241

**Closed by urcades** 2023-04-28 02:23 UTC
Labels: bug
