### ISSUE TITLE
Channels not Sorting

### ISSUE THREAD

**Issue by marisarow** [tloncorp/landscape-apps#1830] opened 2023-01-30 21:38 UTC
**Describe the bug, optionally with screenshots**
Channels in Groups are not sorting. I cannot sort A to Z, nor Arranged, nor Recent.

**Comment by jamesacklin** [comment] 2023-01-30 21:56
Duplicate of #1812, fixed by #1813.

**Closed by jamesacklin** 2023-01-30 21:56 UTC
Labels: bug
