### ISSUE TITLE
Can't change Group cover

### ISSUE THREAD

**Issue by ngzax** [tloncorp/landscape-apps#1409] opened 2022-12-09 21:18 UTC
**Describe the bug, optionally with screenshots**It looks like I can't change any of the attributes of my Group. In particular I am trying to add a cover. I click the button and put in the url, but clicking the "Save" button does nothing. This does work on my other group, The Great North.

<img width="956" alt="Screen Shot 2022-12-09 at 4 10 24 PM" src="https://user-images.githubusercontent.com/87197/206797101-730fbc9d-cfb7-4d04-8f17-18e6efecde47.png">

I don't see an error in the browser when clicking the button, but I do see this when loading the page:

<img width="1188" alt="Screen Shot 2022-12-09 at 4 13 33 PM" src="https://user-images.githubusercontent.com/87197/206797243-c8a43c40-e67d-4bae-8d46-6aa6426cf0f7.png">

**Expected behavior**
Settings saved.

**Additional context:**
- Ship type (comet/moon/planet/star/galaxy)
planet, ~winter-paches, though the group is on a star, ~darlur. tried in both places, no difference.
 
- Instance type (Tlon-hosted/self-hosted with Port/CLI)
self-hosted CLI on Oracle VM

- OS/browser (Safari on MacOS, Chrome on Windows, Firefox on Linux, etc.)
Tried on both Chrome and Brave on MacOS

**Comment by patosullivan** [comment] 2022-12-09 21:20
Appears to be a duplicate of #1386

**Comment by patosullivan** [comment] 2022-12-09 21:20
(sorry, I asked for you to create this, didn't realize we already had one)

**Comment by ngzax** [comment] 2022-12-09 21:54
np! i'll close it. i have found a couple more groups i can't change as well so it's not just bookends.

**Comment by ngzax** [comment] 2022-12-09 21:55
dupe

**Comment by ngzax** [comment] 2022-12-09 21:58
oh well, looks like i can't close. carry on! :)

**Comment by rcrdlbl** [comment] 2022-12-09 21:59
duplicate of #1386

**Closed by rcrdlbl** 2022-12-09 21:59 UTC
Labels: bug
