### ISSUE TITLE
Multiparty DM state incorrect

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/landscape-apps#2423] opened 2023-04-27 15:14 UTC
**Describe the bug, optionally with screenshots**
Multiparty DM shows one member both as joined and as being pending twice. The member in the mixed state was the last to join the DM.

https://drive.google.com/file/d/1tUd-rfNwMZVSHEsQksQwiZWDIf_BhtbI/view?usp=sharing

**Comment by jamesacklin** [comment] 2023-04-27 15:20
Duplicate of #2408, @arthyn will be in touch to debug 1:1

**Closed by jamesacklin** 2023-04-27 15:20 UTC
Labels: bug
