### ISSUE TITLE
talk: TypeError every time I open Talk

### ISSUE THREAD

**Issue by bonbud-macryg** [tloncorp/landscape-apps#2418] opened 2023-04-27 10:03 UTC
Looks closely related to #2363. As with that issue Groups works fine.

Talk hash: `0vk.fqq3n.k68ie.aspdr.svh6n.qi22g.gj3q7.bgjci.qj0o7.pmr5p.7f8ad`

```
TypeError: Cannot destructure property 'title' of 'e' as it is undefined.
    at ae (http://100.93.206.31/apps/talk/assets/grid.3f745d3b.js:1:1610)
    at Ko (http://100.93.206.31/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:52865)
    at ea (http://100.93.206.31/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:8695)
    at Js (http://100.93.206.31/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:935)
    at Qf (http://100.93.206.31/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:866)
    at sn (http://100.93.206.31/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:725)
    at mo (http://100.93.206.31/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:21:10863)
    at http://100.93.206.31/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:38697
    at e.unstable_runWithPriority (http://100.93.206.31/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:8:3835)
    at st (http://100.93.206.31/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:38475)
```

**Comment by patosullivan** [comment] 2023-04-27 11:44
Yeah, this is a dupe of #2363, will close in favor of that one.

**Closed by patosullivan** 2023-04-27 11:44 UTC
Labels: bug
