### ISSUE TITLE
Can't update group info as a non-host admin

### ISSUE THREAD

**Issue by vvisigoth** [tloncorp/landscape-apps#1474] opened 2022-12-13 23:11 UTC
**Describe the bug, optionally with screenshots**
I am an admin of a group but not its host. If I try to modify the group metadata, say "banner color," the button spins but never updates.

**Comment by jamesacklin** [comment] 2022-12-14 13:11
Dupe of #1386

**Closed by jamesacklin** 2022-12-14 13:11 UTC
Labels: bug
