### ISSUE TITLE
"Unhandled message type" when clicking on text channel in a group

### ISSUE THREAD

**Issue by larryshouse** [tloncorp/landscape-apps#2315] opened 2023-04-17 18:05 UTC
```
kn@https://pinwyl-doswen.tlon.network/apps/groups/assets/index.8af1b904.js:45:71331
Kl@https://pinwyl-doswen.tlon.network/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:19:52884
mf@https://pinwyl-doswen.tlon.network/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:23:8723
pf@https://pinwyl-doswen.tlon.network/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:23:949
yg@https://pinwyl-doswen.tlon.network/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:23:877
rn@https://pinwyl-doswen.tlon.network/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:23:730
sl@https://pinwyl-doswen.tlon.network/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:21:10884
Ud/<@https://pinwyl-doswen.tlon.network/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:19:38716
e.unstable_runWithPriority@https://pinwyl-doswen.tlon.network/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:8:3811
_r@https://pinwyl-doswen.tlon.network/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:19:38494
Ud@https://pinwyl-doswen.tlon.network/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:19:38664
ir@https://pinwyl-doswen.tlon.network/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:19:38597
sf@https://pinwyl-doswen.tlon.network/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:21:11312
batchSet@https://pinwyl-doswen.tlon.network/apps/groups/assets/index.8af1b904.js:36:55949
initialize@https://pinwyl-doswen.tlon.network/apps/groups/assets/index.8af1b904.js:36:54712

```

**Comment by larryshouse** [comment] 2023-04-17 18:06
Encountered error: Unhandled message type: {"code":"Intro:\n \nAm, F, C...\nF, Em7, C, Em7, F\nEm7, C, Dm, F, G\n \nVerse:\n \nAm\nSomeday\n C Em7 F\nI know we'll meet again\n Em7 C Em7 F\nWithout knowing exactly when\n G C\nAnd until then\n Dm F G\nTake care of yourself my friend\n \n Am\nIf you tell it to my heart\n F\nwhere would you start?\n G\nWith that truth we shared\n Am F G\nor the lies that drove us apart?\n \n Am\nIf you tell it to my heart\n F\nwhere would you start?\n G\nWith that truth we shared\n Am F C\nor the lies that drove us apart?\n \n Am\nIf you tell it to my heart\n F\nwhere would you start?\n G\nWith that truth we shared\n Am F G\nor the lies that drove us apart?\n \nOutro:\n \nC\nHea-a-a-art\n G\nTell it to my heart\n \nAm, F, G, C (ad infinitum)"}

**Comment by larryshouse** [comment] 2023-04-17 18:10
![error_window_screenshot](https://user-images.githubusercontent.com/130805477/232573248-ef2893a2-d96d-4e46-9fc1-2d26dc2cbc2f.jpg)

**Comment by jamesacklin** [comment] 2023-04-17 18:57
Duplicate of #2314

**Closed** 2023-04-17 18:57 UTC
Labels: bug

**Comment by larryshouse** [comment] 2023-04-17 19:30
Thanks, James!
