### ISSUE TITLE
chat: new messages banner often doesn't jump to new messages when clicked

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#1455] opened 2022-12-13 04:05 UTC
**Describe the bug, optionally with screenshots**

The banner that says how many new messages there are in a channel says "click to view" or some such thing but often doesn't do anything when you click it. Also it doesn't clear unreads when you click the X

**To Reproduce**
1. got to channel with new messages
2. Click on unread messages banner
3. nothing happens
4. click X to dismiss it
5. also nothing happens

**Expected behavior**
should jump to new messages reliably and should reliably clear unreads when the X is clicked

**Additional context:**
- Ship type planet
- Instance type self-hosted
- OS/browser qutebrowser on arch linux

**Comment by jamesacklin** [comment] 2022-12-14 13:07
Dupe of #1461

**Closed by jamesacklin** 2022-12-14 13:07 UTC
Labels: bug
