### ISSUE TITLE
On Mobile: No way to see or join  unjoined channels of a group

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1364] opened 2022-12-09 00:48 UTC
**Describe the bug, optionally with screenshots**
- Be on mobile
- Be in a group
- Try to see what other (unjoined) channels exist in the group

**Comment by jamesacklin** [comment] 2022-12-09 01:01
Dupe of #1266

**Closed by jamesacklin** 2022-12-09 01:01 UTC
Labels: bug
