### ISSUE TITLE
chat: last reply time for thread often wrong

### ISSUE THREAD

**Issue by patosullivan** [tloncorp/landscape-apps#1451] opened 2022-12-12 22:11 UTC
It'll show seemingly arbitrary amounts of time, in minutes, rather than the real amount of time since the last post.

**Comment by lycurgus** [comment] 2022-12-13 02:38
I think it shows the original thread creation time, rather than the time of the latest post? So if the first reply (creating the thread) was 4 hours ago, and the latest reply was 10 minutes ago, it will still show "4 hours". 

Seems to align with what I've observed, at least.

**Comment by jamesacklin** [comment] 2023-01-05 17:58
Dupe of #1579

**Closed** 2023-01-05 17:58 UTC
Labels: bug, chat
