### ISSUE TITLE
Failed to fetch dynamically imported module: DiaryAddNote.fbf168ef.js

### ISSUE THREAD

**Issue by sigilante** [tloncorp/landscape-apps#1853] opened 2023-02-02 03:38 UTC
`Add Note` usage fails repeatedly on a notebook I have perms to write in.

I am on ~binnec-dozzod-marzod.

```
TypeError: Failed to fetch dynamically imported module: http://100.105.215.33:8080/apps/groups/assets/DiaryAddNote.fbf168ef.js
```

**Comment by jamesacklin** [comment] 2023-02-02 13:51
Should be fixed by #1829, but @patosullivan can you verify?

**Comment by patosullivan** [comment] 2023-02-02 14:32
This is actually should be fixed by deprecating janeway for releases and the work in #1829. Dupe of #1733.

**Closed** 2023-02-02 15:43 UTC
Labels: bug
