### ISSUE TITLE
Cannot read properties of undefined (reading 'NODE_ENV')

### ISSUE THREAD

**Issue by vietkorochi** [tloncorp/landscape-apps#2649] opened 2023-06-26 03:34 UTC
```
TypeError: Cannot read properties of undefined (reading 'NODE_ENV')
    at F4e (https://lomwel-rilwyn.tlon.network/apps/grid/assets/index.78c07bfe.js:251:44843)
    at At (https://lomwel-rilwyn.tlon.network/apps/grid/assets/index.78c07bfe.js:251:44416)
    at y0 (https://lomwel-rilwyn.tlon.network/apps/grid/assets/index.78c07bfe.js:251:73911)
    at w3e (https://lomwel-rilwyn.tlon.network/apps/grid/assets/index.78c07bfe.js:251:77004)
    at C3e (https://lomwel-rilwyn.tlon.network/apps/grid/assets/index.78c07bfe.js:251:77337)
    at Q3e (https://lomwel-rilwyn.tlon.network/apps/grid/assets/index.78c07bfe.js:252:27364)
    at GS (https://lomwel-rilwyn.tlon.network/apps/grid/assets/index.78c07bfe.js:85:52997)
    at bP (https://lomwel-rilwyn.tlon.network/apps/grid/assets/index.78c07bfe.js:89:8819)
    at gP (https://lomwel-rilwyn.tlon.network/apps/grid/assets/index.78c07bfe.js:89:951)
    at uj (https://lomwel-rilwyn.tlon.network/apps/grid/assets/index.78c07bfe.js:89:879)
```

**Comment by jamesacklin** [comment] 2023-06-26 12:57
Thanks; before I mark this as a duplicate of https://github.com/tloncorp/landscape-apps/issues/2579, what were you doing when you experienced this error?

**Comment by jamesacklin** [comment] 2023-06-29 13:05
Closing as duplicate of #2579.

**Closed by jamesacklin** 2023-06-29 13:05 UTC
