### ISSUE TITLE
Unable to preload CSS for /apps/groups/assets/DiaryAddNote.ce8f858f.css

### ISSUE THREAD

**Issue by marisarow** [tloncorp/landscape-apps#1862] opened 2023-02-02 19:15 UTC
```
Error: Unable to preload CSS for /apps/groups/assets/DiaryAddNote.ce8f858f.css
    at HTMLLinkElement.<anonymous> (https://riprud-tidmel.tlon.network/apps/groups/assets/index.e52fdbc4.js:97:21699)
```

**Comment by jamesacklin** [comment] 2023-02-02 19:27
Duplicate of #1733, addressed in the next round of CI/CD pipeline fixes.

**Closed by jamesacklin** 2023-02-02 19:27 UTC
Labels: bug
