### ISSUE TITLE
landscape: groups 1 in sysprefs sidebar, app ordering should be sensical

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1420] opened 2022-12-10 12:35 UTC
![image](https://user-images.githubusercontent.com/748181/206855373-da0d88d4-8784-4e37-a967-5d9b025e7809.jpeg)

**Comment by zalberico** [comment] 2022-12-10 17:49
Mostly a duplicate of https://github.com/tloncorp/landscape-apps/issues/1370

**Comment by jamesacklin** [comment] 2022-12-10 23:16
> Mostly a duplicate of https://github.com/tloncorp/landscape-apps/issues/1370

Partial. Could be rolled into one, wanted to capture anyways

**Closed** 2022-12-15 16:13 UTC
Labels: ux
