### ISSUE TITLE
Cannot read properties of undefined (reading 'sects')

### ISSUE THREAD

**Issue by thelifeandtimes** [tloncorp/landscape-apps#1519] opened 2022-12-15 19:36 UTC
no idea what is happening here, but the dialog box prompted me to submit an issue so here we go:
```
TypeError: Cannot read properties of undefined (reading 'sects')
    at c2t (https://star.tocwex.io/apps/escape/assets/index.eaacb2cf.js:1137:78326)
    at bR (https://star.tocwex.io/apps/escape/assets/index.eaacb2cf.js:93:53297)
    at bae (https://star.tocwex.io/apps/escape/assets/index.eaacb2cf.js:97:8857)
    at mae (https://star.tocwex.io/apps/escape/assets/index.eaacb2cf.js:97:964)
    at sSe (https://star.tocwex.io/apps/escape/assets/index.eaacb2cf.js:97:887)
    at Kw (https://star.tocwex.io/apps/escape/assets/index.eaacb2cf.js:97:737)
    at m_ (https://star.tocwex.io/apps/escape/assets/index.eaacb2cf.js:95:10947)
    at ep (https://star.tocwex.io/apps/escape/assets/index.eaacb2cf.js:95:8466)
    at k8 (https://star.tocwex.io/apps/escape/assets/index.eaacb2cf.js:97:15965)
    at https://star.tocwex.io/apps/escape/assets/index.eaacb2cf.js:97:17629
```
Happened in EScape but don't think it's an EScape issue. Page was running fine. Left home, opened up laptop at a coffee shop, gave me the header bar prompting me to reconnect and then took me to the error dialog.

**Comment by jamesacklin** [comment] 2022-12-15 19:39
Thanks - dupe of #1513 but you weren't in the channel editor, which is useful info.

**Closed by jamesacklin** 2022-12-15 19:39 UTC
Labels: bug
