### ISSUE TITLE
refs: pasting into ChatInput simultaneously populates ref in both ChatWindow and ChatThread

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#1418] opened 2022-12-10 04:49 UTC
https://user-images.githubusercontent.com/16504501/206829673-29614295-3510-4106-91d8-60f5e7faeb57.mp4

**Comment by patosullivan** [comment] 2022-12-14 17:26
FYI, this seems to be caused by this bug in tiptap: https://github.com/ueberdosis/tiptap/issues/2694

The suggested workaround (calling .configure() on the extension and calling useEditor separately for each instance) doesn't seem to fix it in our case, though.

Going to continue hitting my head against this wall, just wanted to update.

**Comment by jamesacklin** [comment] 2023-01-23 17:11
Fixed by #1760

**Closed** 2023-01-23 17:11 UTC
Labels: bug, chat
