### ISSUE TITLE
groups: incorrectly over-permissioned as admin, can delete messages

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape-apps#1479] opened 2022-12-14 02:26 UTC
I'm seeing an odd bug where I am able to delete messages even in groups of which I was never an admin. In the Members list I am listed as an admin. I know of other users with the same bug, except that I do not appear as an admin to them. So each user appears to himself to be an admin and is able to delete posts.

Maybe it's because permissions were changed during migration?

__Originally posted by @willbach in https://github.com/tloncorp/landscape-apps/issues/1428#issuecomment-1348523865__

**Comment by jamesacklin** [comment] 2022-12-14 02:32
@willbach Do you have a base hash for both %landscape and %groups on your ship?

Do others in the group see the deletion of the messages that aren't yours?

**Comment by tomholford** [comment] 2022-12-14 03:00
Notes from investigation so far.

Here's the logic for rendering the Delete button:
```tsx
      {window.our === writ.memo.author ? (
        <IconButton
          icon={<XIcon className="h-6 w-6 text-red" />}
          label="Delete"
          showTooltip
          action={onDelete}
        />
      ) : null}
```

Here's the click handler:
```ts
  const onDelete = () => {
    useChatState.getState().delMessage(whom, writ.seal.id);
  };
```

And here's the poke request:
```ts
    delMessage: (whom, id) => {
      const isDM = whomIsDm(whom);
      const diff = { del: null };
      if (isDM) {
        api.poke(dmAction(whom, diff, id));
      } else {
        api.poke(chatWritDiff(whom, id, diff));
      }
    },
```

So far, no validation is performed besides the initial rendering logic (ie, only render the delete button if `author.memo.writ` is equal to `our`). Now exploring the backend hoon to see what validation is performed there.

**Comment by tomholford** [comment] 2022-12-14 08:10
Admittedly not a hoon expert (could use one to confirm this analysis), but this seems to be what's going on in the backend (`chat.hoon`):

In the `ca-update` arm that handles the `%writs %del` poke , there's a `?>` assertion that calls `ca-can-write` before delegating to `ca-core`:
```hoon
  ++  ca-update
    |=  [=time d=diff:c]
    ?>  ca-can-write
    ...
    ::
        %writs
      =.  pact.chat  (reduce:ca-pact time p.d)
      =.  cor  (give-brief flag/flag ca-brief)
      ?-  -.q.p.d  
          ?(%del %add-feel %del-feel)  ca-core
```

In `ca-can-write`:  first the group's flag's patp (`p.flag`) is compared against the bowl's src (in other words, if the owner is making the request, return true). otherwise, it scries into the groups agent and retrieves the groups vessel. Then, it checks if the `writers.perm.chat` list is empty; if so, return true. Otherwise, it finally will return a boolean indicating whether or not the `sects.vessel` is in the same `writers` list.
```hoon
  ++  ca-groups-scry
    =*  group  group.perm.chat
    /(scot %p our.bowl)/groups/(scot %da now.bowl)/groups/(scot %p p.group)/[q.group]
  ::
  ++  ca-can-write
    ?:  =(p.flag src.bowl)  &
    =/  =path
      %+  welp  ca-groups-scry
      /fleet/(scot %p src.bowl)/vessel/noun
    =+  .^(=vessel:fleet:g %gx path)
    ?:  =(~ writers.perm.chat)  &
    !=(~ (~(int in writers.perm.chat) sects.vessel))
  ::
```

So, if this bug is indeed reproducible, here are some potential explanations for the observed behavior:
- the requesting user owns the group
- during the migration, the requesting user was unexpectedly added to a `sect` (aka role) that has write permission
-  if it's possible that a `chat` could be bunted with no `writers.perm` initialized, then the line `?:  =(~ writers.perm.chat)  &` would always return true

**Comment by liam-fitzgerald** [comment] 2022-12-14 18:50
This should be fixed by the rewatching fix

**Closed** 2022-12-15 16:14 UTC
