### ISSUE TITLE
Channels in talk should somehow show what group they're from in the list

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1379] opened 2022-12-09 01:16 UTC
**Describe the bug, optionally with screenshots**
- Multiple groups have channels with the same name (typically General)
- Currently you can only tell what group by the icon (many groups don't have one) or once you click into it
- It'd be good to have some way to know what the parent group of the channel is in talk
- See example of three generals below
<img width="237" alt="Screenshot 2022-12-08 at 5 16 08 PM" src="https://user-images.githubusercontent.com/441466/206600858-c92b73eb-708c-47e9-aa26-ccfb1e313b3a.png">

**Comment by jamesacklin** [comment] 2022-12-09 01:24
Dupe of #496

**Closed by jamesacklin** 2022-12-09 01:24 UTC
Labels: bug
